### ISSUE TITLE
Get the jar on Maven Central

### ISSUE THREAD

**Issue by mihneadb** [uberVU/elasticsearch-river-github#1]
This will make the plugin easy to install (just `bin/plugin --install org.elasticsearch/elasticsearch-river-github`).

Guide is here[1].

[1] https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

**Comment by mihneadb** [comment]
Issue opened: https://issues.sonatype.org/browse/OSSRH-8495

**Comment by mihneadb** [comment]
@mishu- please check this [reply](https://issues.sonatype.org/browse/OSSRH-8495?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=209418#comment-209418). I saw that the other community elasticsearch plugins use org.elasticsearch as a groupId, but maybe they are not published on Maven Central. Maybe it would make more sense to go with com.ubervu?

**Comment by mishu-** [comment]
just use com.ubervu :)

On Tue, Jan 21, 2014 at 9:12 PM, Mihnea Dobrescu-Balaur <
notifications@github.com> wrote:

> @mishu- https://github.com/mishu- please check this replyhttps://issues.sonatype.org/browse/OSSRH-8495?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=209418#comment-209418.
> I saw that the other community elasticsearch plugins use org.elasticsearch
> as a groupId, but maybe they are not published on Maven Central. Maybe it
> would make more sense to go with com.ubervu?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/uberVU/elasticsearch-river-github/issues/1#issuecomment-32949511
> .

## 

Mihai Oprea

University of Pennsylvania, Class of 2009
School of Engineering and Applied Sciences
Masters of Science and Engineering in Computer and Information Science
Bachelor of Science and Engineering in Computer and Information Science
RO: +40 (72) 000 2704

**Comment by mihneadb** [comment]
Ok!

// yay, more folder renaming! :)

On Tue, Jan 21, 2014 at 11:10 PM, Mihai Oprea notifications@github.comwrote:

> just use com.ubervu :)
> 
> On Tue, Jan 21, 2014 at 9:12 PM, Mihnea Dobrescu-Balaur <
> notifications@github.com> wrote:
> 
> > @mishu- https://github.com/mishu- please check this reply<
> > https://issues.sonatype.org/browse/OSSRH-8495?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=209418#comment-209418>.
> > 
> > I saw that the other community elasticsearch plugins use
> > org.elasticsearch
> > as a groupId, but maybe they are not published on Maven Central. Maybe
> > it
> > would make more sense to go with com.ubervu?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/uberVU/elasticsearch-river-github/issues/1#issuecomment-32949511>
> > 
> > .
> 
> ## 
> 
> Mihai Oprea
> 
> University of Pennsylvania, Class of 2009
> School of Engineering and Applied Sciences
> Masters of Science and Engineering in Computer and Information Science
> Bachelor of Science and Engineering in Computer and Information Science
> RO: +40 (72) 000 2704
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/uberVU/elasticsearch-river-github/issues/1#issuecomment-32963770
> .

## 

Mihnea Dobrescu-Balaur

**Comment by mihneadb** [comment]
Ok, promoted the jar as release. Waiting on the sync to maven-central.

https://issues.sonatype.org/browse/OSSRH-8495?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=209418#comment-209521

**Comment by mihneadb** [comment]
Done. It's com.ubervu/elasticsearch-river-github (ver. 1.0.0)
