### ISSUE TITLE
GitHubRiver.DataStream#isRunning should be volatile

### ISSUE THREAD

**Issue by andreisavu** [uberVU/elasticsearch-river-github#7]
Otherwise that thread may never close on multi-cpu systems.

Also you may want to consider using breaking out of the while(isRunning) loop on InterruptedException.

**Comment by andreisavu** [comment]
Good article on how to deal with interrupted exceptions: 
http://www.ibm.com/developerworks/library/j-jtp05236/

**Comment by mihneadb** [comment]
Thanks for bringing this up!

Any chance you'd like to submit a pull request for fixing this? :)

**Comment by andreisavu** [comment]
I don't really have the time. This is just a suggestion after taking a quick look at the code.

**Comment by mihneadb** [comment]
Was worth a shot :). Thanks!

On Mon, Mar 3, 2014 at 7:28 PM, Andrei Savu notifications@github.comwrote:

> I don't really have the time. This is just a suggestion after taking a
> quick look at the code.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/uberVU/elasticsearch-river-github/issues/7#issuecomment-36541274
> .

## 

Mihnea Dobrescu-Balaur
